image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_TLS_CERTDIR: ""

#chaches the files necessary to run the project for all stages so that i.e. test does not need to download all libs
#again
cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test

maven-build:
  image: maven
  services:
    - postgres
  stage: build
  script:
    - mvn compile
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/*.war

java:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml